name: webPlug
main: me.bukkit.firstflames.websitePlugin.WebsiteCommand
version: 1.0
commands:
   website:
      description: Display's website address
      usage: /<command>
   godGo:
      description: In testing
      usage: /<command>

